import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';

import { SpssVariableEditor } from '@/components/survey-builder/spss-variable-editor';

describe('SpssVariableEditor', () => {
  const defaultProps = {
    questionCode: 'Q1',
    autoGeneratedCode: 'Q1',
    isCustom: false,
    onChangeCode: vi.fn(),
    onReset: vi.fn(),
  };

  it('현재 변수명을 표시한다', () => {
    render(<SpssVariableEditor {...defaultProps} />);
    expect(screen.getByDisplayValue('Q1')).toBeInTheDocument();
  });

  it('입력이 항상 활성화되어 있다', () => {
    render(<SpssVariableEditor {...defaultProps} isCustom={false} />);
    expect(screen.getByRole('textbox')).toBeEnabled();
  });

  it('자동 모드일 때 자동 생성된 값이 input에 표시된다', () => {
    render(<SpssVariableEditor {...defaultProps} questionCode="" autoGeneratedCode="Q3" />);
    expect(screen.getByDisplayValue('Q3')).toBeInTheDocument();
  });

  it('변수명을 수정하면 onChangeCode가 호출된다', async () => {
    const onChangeCode = vi.fn();
    render(
      <SpssVariableEditor
        {...defaultProps}
        questionCode="Q1"
        autoGeneratedCode="Q1"
        onChangeCode={onChangeCode}
      />,
    );

    const input = screen.getByRole('textbox');
    await userEvent.type(input, 'X');
    // 'Q1' + 'X' = 'Q1X' !== 'Q1' → isCustom=true
    expect(onChangeCode).toHaveBeenCalledWith('Q1X', true);
  });

  it('자동 생성 값과 동일한 값이면 isCustom=false로 호출된다', async () => {
    const onChangeCode = vi.fn();
    // questionCode가 비어있으면 displayValue는 autoGeneratedCode 'Q'
    render(
      <SpssVariableEditor
        {...defaultProps}
        questionCode=""
        autoGeneratedCode="Q"
        isCustom={false}
        onChangeCode={onChangeCode}
      />,
    );

    const input = screen.getByRole('textbox');
    // displayValue가 'Q' (autoGeneratedCode). 'Q'를 타이핑하면 'QQ' → isCustom=true
    await userEvent.type(input, 'Q');
    expect(onChangeCode).toHaveBeenLastCalledWith('QQ', true);
  });

  it('커스텀 모드일 때 초기화 버튼이 표시된다', () => {
    render(<SpssVariableEditor {...defaultProps} isCustom={true} questionCode="SQ-CUSTOM" />);
    expect(screen.getByTitle('자동 변수명으로 초기화')).toBeInTheDocument();
  });

  it('자동 모드일 때 초기화 버튼이 표시되지 않는다', () => {
    render(<SpssVariableEditor {...defaultProps} isCustom={false} />);
    expect(screen.queryByTitle('자동 변수명으로 초기화')).not.toBeInTheDocument();
  });

  it('초기화 버튼 클릭 시 onReset이 호출된다', async () => {
    const onReset = vi.fn();
    render(
      <SpssVariableEditor {...defaultProps} isCustom={true} questionCode="SQ-CUSTOM" onReset={onReset} />,
    );

    await userEvent.click(screen.getByTitle('자동 변수명으로 초기화'));
    expect(onReset).toHaveBeenCalled();
  });

  it('커스텀 모드일 때 자동 생성 값을 힌트로 표시한다', () => {
    render(
      <SpssVariableEditor {...defaultProps} isCustom={true} questionCode="SQ-CUSTOM" autoGeneratedCode="Q5" />,
    );
    expect(screen.getByText('자동: Q5')).toBeInTheDocument();
  });

  it('자동 모드일 때 "자동 생성됨" 텍스트를 표시한다', () => {
    render(<SpssVariableEditor {...defaultProps} isCustom={false} />);
    expect(screen.getByText('자동 생성됨')).toBeInTheDocument();
  });

  it('옵션 숫자코드를 표시한다', () => {
    const options = [
      { id: 'o1', label: '남성', value: 'o1', spssNumericCode: 1 },
      { id: 'o2', label: '여성', value: 'o2', spssNumericCode: 2 },
    ];
    render(<SpssVariableEditor {...defaultProps} options={options} />);
    expect(screen.getByText('1')).toBeInTheDocument();
    expect(screen.getByText('남성')).toBeInTheDocument();
    expect(screen.getByText('2')).toBeInTheDocument();
    expect(screen.getByText('여성')).toBeInTheDocument();
  });

  it('옵션이 없으면 숫자코드 영역을 렌더하지 않는다', () => {
    render(<SpssVariableEditor {...defaultProps} />);
    expect(screen.queryByText('옵션 코드')).not.toBeInTheDocument();
  });
});
